frontend/haidispeechreco/urls.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path
from . import views

urlpatterns = [
    path('actions', views.ActionsList.as_view(), name='actions-list'),
    path('actions/create', views.ActionCreate.as_view(), name='action-create'),
    path('actions/<int:pk>/edit', views.ActionEdit.as_view(), name='action-edit'),
    path('actions/<int:pk>/detail', views.ActionDetail.as_view(), name='action-detail'),
    path('actions/<int:pk>/delete', views.ActionDelete.as_view(), name='action-delete'),
    path('actions/<int:pk>/keyphrase/create', views.KeyphraseCreate.as_view(), name='keyphrase-create'),
    path('keyphrases/<int:pk>/edit', views.KeyphraseEdit.as_view(), name='keyphrase-edit'),
    path('keyphrases/<int:pk>/delete', views.KeyphraseDelete.as_view(), name='keyphrase-delete'),
    path('actions/<int:pk>/answer/create', views.AnswerCreate.as_view(), name='answer-create'),
    path('answers/<int:pk>/edit', views.AnswerEdit.as_view(), name='answer-edit'),
    path('answers/<int:pk>/delete', views.AnswerDelete.as_view(), name='answer-delete'),
    path('keyphrases', views.KeyphrasesList.as_view(), name='keyphrases-list'),
]

frontend/haidiui/urls.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib import admin
from django.urls import path, include
import os
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('login/logout', views.LogoutView.as_view(), name='logout'),
    path('debug', views.Debug.as_view(), name='debug'),
    path('screen', views.MainScreen.as_view(), name='screen'),
    path('hsr/', include(("haidispeechreco.urls", "hsr"), namespace="hsr")),
]


BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SPOOL_DIR = os.path.join(BASE_DIR, "spool")
PIDFILE = os.path.join(SPOOL_DIR, "frontend_pidfile")
_pid = open(PIDFILE, "w")
_pid.write(str(os.getpid()))
_pid.close()

frontend/haidispeechreco/models.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError


class Language(models.Model):
    name = models.CharField(max_length=10, verbose_name=_("Name"))

    api_code = models.CharField(max_length=20, verbose_name=_("API Language code"), unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name", )
        verbose_name = _("language")
        verbose_name_plural = _("languages")


class Action(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"), unique=True)

    code = models.TextField(
        verbose_name=_("Python code"),
        help_text=_("Override the \"response\" variable to change the default response"),
        null=True,
        blank=True
    )

    emotions =  [
        ["1", _("All leds ON")],
        ["2", _("All leds OFF")],
        ["3", _("Happy")],
        ["4", _("Sad")],
        ["5", _("Angry")]
    ]

    emotion = models.CharField(max_length=1, choices=emotions)

    @property
    def emotion_name(self):
        for i in self.emotions:
            if i[0] == self.emotion:
                return i[1]

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name", )
        verbose_name = _("action")
        verbose_name_plural = _("actions")


class Keyphrase(models.Model):
    action = models.ForeignKey(Action, verbose_name=_("Action"), on_delete=models.CASCADE)

    language = models.ForeignKey(Language, verbose_name=_("Language"), on_delete=models.CASCADE)

    phrase = models.TextField(verbose_name=_("Phrase"))

    def __str__(self):
        return "%s (%s)" % (self.phrase, self.action.name)

    def clean(self):
        if Keyphrase.objects.filter(language=self.language, phrase=self.phrase).exists():
            raise ValidationError("Another keyphrase with the same language and phrase already exists.")

    class Meta:
        ordering = ("action", "language", "phrase")
        verbose_name = _("keyphrase")
        verbose_name_plural = _("keyphrases")


class Answer(models.Model):
    action = models.ForeignKey(Action, verbose_name=_("Action"), on_delete=models.CASCADE)

    language = models.ForeignKey(Language, verbose_name=_("Language"), on_delete=models.CASCADE)

    answer = models.TextField(verbose_name=_("Answer"))

    custom_answer = models.TextField(verbose_name=_("Custom answer"), null=True, blank=True)

    def __str__(self):
        return "%s (%s)" % (self.action.name, self.language.name)

    def clean(self):
        if Answer.objects.filter(language=self.language, answer=self.answer).exists():
            raise ValidationError("Another answer with the same language and phrase already exists.")

    class Meta:
        ordering = ("action", "language")
        verbose_name = _("answer")
        verbose_name_plural = _("answers")

frontend/haidispeechreco/forms.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from . import models


class EditActionForm(forms.ModelForm):
    class Meta:
        model = models.Action
        fields = ["name", "code", "emotion"]


class EditKeyphraseForm(forms.ModelForm):
    class Meta:
        model = models.Keyphrase
        fields = ["action", "language", "phrase"]


class EditAnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ["action", "language", "answer", "custom_answer"]

frontend/haidispeechreco/views.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from .models import Action, Keyphrase, Answer
from . import forms


class ActionsList(LoginRequiredMixin, ListView):
    model = Action
    template_name = "hsr/actions.html"


class ActionDetail(LoginRequiredMixin, DetailView):
    model = Action
    template_name = "hsr/action.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["keyphrases"] = Keyphrase.objects.filter(action=context["object"])
        context["answers"] = Answer.objects.filter(action=context["object"])
        return context


class ActionCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Action
    form_class = forms.EditActionForm
    template_name = "hsr/action_create.html"
    success_message = _("Action created successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.pk})


class ActionEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Action
    form_class = forms.EditActionForm
    template_name = "hsr/action_edit.html"
    success_message = _("Action edited successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.pk})


class ActionDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Action
    template_name = "hsr/action_delete.html"
    success_url = reverse_lazy("hsr:actions-list")
    success_message = _("Action deleted successfully.")


class KeyphraseCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Keyphrase
    form_class = forms.EditKeyphraseForm
    template_name = "hsr/action_create.html"
    success_message = _("Keyphrase created successfully.")

    def get_initial(self):
        act = get_object_or_404(Action, pk=self.kwargs.get("pk"))
        return {"action": act}

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class KeyphraseEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Keyphrase
    form_class = forms.EditKeyphraseForm
    template_name = "hsr/keyphrase_edit.html"
    success_message = _("Keyphrase edited successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class KeyphraseDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Keyphrase
    template_name = "hsr/keyphrase_delete.html"
    success_message = _("Keyphrase deleted successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class AnswerCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Answer
    form_class = forms.EditAnswerForm
    template_name = "hsr/answer_create.html"
    success_message = _("Answer created successfully.")

    def get_initial(self):
        act = get_object_or_404(Action, pk=self.kwargs.get("pk"))
        return {"action": act}

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class AnswerEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Answer
    form_class = forms.EditAnswerForm
    template_name = "hsr/answer_edit.html"
    success_message = _("Answer edited successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class AnswerDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Answer
    template_name = "hsr/answer_delete.html"
    success_message = _("Answer deleted successfully.")

    def get_success_url(self):
        return reverse_lazy("hsr:action-detail", kwargs={"pk": self.object.action.pk})


class KeyphrasesList(LoginRequiredMixin, ListView):
    model = Keyphrase
    template_name = "hsr/keyphrases.html"

frontend/haidispeechreco/templates/hsr/action.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{{object.name}}{% endblock %}
{% block content %}
<h2>{% trans "Action" %}: {{object.name}}</h2>
<br>
<div class="row">
  <div class="col-lg-6">
    {% trans "Emotion" %}: {{object.emotion_name}}
  </div>
  <div class="col-lg-6 align-right">
    <a href="{% url 'hsr:action-edit' pk=object.pk %}" class="btn btn-lg btn-warning white">
      <i class="fas fa-pencil-alt"></i>
    </a>
    <a href="{% url 'hsr:action-delete' pk=object.pk %}" class="btn btn-lg btn-danger white">
      <i class="fas fa-trash"></i>
    </a>
  </div>
</div>
<br>
<div class="row pb-1">
  <div class="col-lg-6">
    <h3>{% trans "Keyphrases" %}</h3>
  </div>
  <div class="col-lg-6 align-right">
    <a href="{% url 'hsr:keyphrase-create' pk=object.pk %}" class="btn btn-lg btn-success">
      <i class="fas fa-plus-circle" aria-hidden="true"></i> {% trans "Add" %}
    </a>
  </div>
</div>
<table class="table table-striped" id="keyphrases-tab">
  <thead>
    <tr>
      <th>{% trans "Language" %}</th>
      <th>{% trans "Phrase" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for e in keyphrases %}
    <tr>
      <td>{{e.language.name}} ({{e.language.api_code}})</td>
      <td>{{e.phrase}}</td>
      <td class="align-right">
        <a href="{% url 'hsr:keyphrase-edit' pk=e.pk %}" class="btn btn-lg btn-warning white">
          <i class="fas fa-pencil-alt"></i>
        </a>
        <a href="{% url 'hsr:keyphrase-delete' pk=e.pk %}" class="btn btn-lg btn-danger white">
          <i class="fas fa-trash"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>


<div class="row pb-1">
  <div class="col-lg-6">
    <h3>{% trans "Answers" %}</h3>
  </div>
  <div class="col-lg-6 align-right">
    <a href="{% url 'hsr:answer-create' pk=object.pk %}" class="btn btn-lg btn-success">
      <i class="fas fa-plus-circle" aria-hidden="true"></i> {% trans "Add" %}
    </a>
  </div>
</div>
<table class="table table-striped" id="answers-tab">
  <thead>
    <tr>
      <th>{% trans "Language" %}</th>
      <th>{% trans "Answer" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for e in answers %}
    <tr>
      <td>{{e.language.name}} ({{e.language.api_code}})</td>
      <td>{{e.answer}}</td>
      <td class="align-right">
        <a href="{% url 'hsr:answer-edit' pk=e.pk %}" class="btn btn-lg btn-warning white">
          <i class="fas fa-pencil-alt"></i>
        </a>
        <a href="{% url 'hsr:answer-delete' pk=e.pk %}" class="btn btn-lg btn-danger white">
          <i class="fas fa-trash"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script type="text/javascript">
$(document).ready(function() {
  $("#answers-tab").DataTable();
  $("#keyphrases-tab").DataTable();
});
</script>

{% endblock %}

frontend/haidispeechreco/templates/hsr/action_create.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Create action" %}{% endblock %}
{% block content %}
<h2>{% trans "Create a new action" %}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/action_delete.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Delete" %} {{object.name}}{% endblock %}
{% block content %}
<h2>{% trans "Really delete action" %} {{object.name}} ?</h2>
<br>
<form action="" method="POST">
{% csrf_token %}
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-danger">
    <i class="fas fa-trash" aria-hidden="true"></i> {% trans "Delete" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.pk %}" class="btn btn-lg btn-success">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/action_edit.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{{object.name}}{% endblock %}
{% block content %}
<h2>{% trans "Edit action" %}: {{object.name}}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.pk %}" class="btn btn-lg btn-danger">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/actions.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Actions" %}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2>{% trans "Actions" %}</h2>
  </div>
  <div class="col-lg-6 align-right">
    <a href="{% url 'hsr:action-create' %}" class="btn btn-lg btn-success">
      <i class="fas fa-plus-circle" aria-hidden="true"></i> {% trans "Add" %}
    </a>
  </div>
</div>
<br>
<table class="table table-striped" id="actions-tab">
  <thead>
    <tr>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Emotion" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for e in object_list %}
    <tr>
      <td>{{e.name}}</td>
      <td>{{e.emotion_name}}</td>
      <td class="align-right">
        <a href="{% url 'hsr:action-detail' pk=e.pk %}" class="btn btn-lg btn-primary">
          <i class="fas fa-arrow-right"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script type="text/javascript">
$(document).ready(function() {
  $("#actions-tab").DataTable();
});
</script>

{% endblock %}

frontend/haidispeechreco/templates/hsr/answer_create.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Create answer" %}{% endblock %}
{% block content %}
<h2>{% trans "Create a new answer" %}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/answer_delete.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Delete" %} {{object.answer}}{% endblock %}
{% block content %}
<h2>{% trans "Really delete answer" %} {{object.answer}} ?</h2>
<br>
<form action="" method="POST">
{% csrf_token %}
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-danger">
    <i class="fas fa-trash" aria-hidden="true"></i> {% trans "Delete" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.action.pk %}" class="btn btn-lg btn-success">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/answer_edit.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{{object.answer}}{% endblock %}
{% block content %}
<h2>{% trans "Edit answer" %}: {{object.answer}}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.action.pk %}" class="btn btn-lg btn-danger">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/keyphrase_create.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Create keyphrase" %}{% endblock %}
{% block content %}
<h2>{% trans "Create a new keyphrase" %}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/keyphrase_delete.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Delete" %} {{object.phrase}}{% endblock %}
{% block content %}
<h2>{% trans "Really delete keyphrase" %} {{object.phrase}} ?</h2>
<br>
<form action="" method="POST">
{% csrf_token %}
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-danger">
    <i class="fas fa-trash" aria-hidden="true"></i> {% trans "Delete" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.action.pk %}" class="btn btn-lg btn-success">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/keyphrase_edit.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{{object.phrase}}{% endblock %}
{% block content %}
<h2>{% trans "Edit keyphrase" %}: {{object.phrase}}</h2>
<br>
<form action="" method="POST">

{% csrf_token %}
<table class="table">
{{form.as_table}}
</table>
<p class="align-right">
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save" aria-hidden="true"></i> {% trans "Save" %}
  </button>
  <a href="{% url 'hsr:action-detail' pk=object.action.pk %}" class="btn btn-lg btn-danger">
    <i class="fas fa-times" aria-hidden="true"></i> {% trans "Undo" %}
  </a>
</p>

</form>

{% endblock %}

frontend/haidispeechreco/templates/hsr/keyphrases.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Keyphrases" %}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2>{% trans "Keyphrases" %}</h2>
  </div>
</div>
<br>
<table class="table table-striped" id="actions-tab">
  <thead>
    <tr>
      <th>{% trans "Phrase" %}</th>
      <th>{% trans "Action" %}</th>
      <th>{% trans "Language" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for e in object_list %}
    <tr>
      <td>{{e.phrase}}</td>
      <td>{{e.action}}</td>
      <td>{{e.language}}</td>
      <td class="align-right">
        <a href="{% url 'hsr:action-detail' pk=e.action.pk %}" class="btn btn-lg btn-primary">
          <i class="fas fa-arrow-right"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script type="text/javascript">
$(document).ready(function() {
  $("#actions-tab").DataTable();
});
</script>

{% endblock %}