frontend/haidispeechreco/urls.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path
from . import views

urlpatterns = [
    path('actions', views.ActionsList.as_view(), name='actions-list'),
    path('actions/create', views.ActionCreate.as_view(), name='action-create'),
    path('actions/<int:pk>/edit', views.ActionEdit.as_view(), name='action-edit'),
    path('actions/<int:pk>/detail', views.ActionDetail.as_view(), name='action-detail'),
    path('actions/<int:pk>/delete', views.ActionDelete.as_view(), name='action-delete'),
    path('actions/<int:pk>/keyphrase/create', views.KeyphraseCreate.as_view(), name='keyphrase-create'),
    path('keyphrases/<int:pk>/edit', views.KeyphraseEdit.as_view(), name='keyphrase-edit'),
    path('keyphrases/<int:pk>/delete', views.KeyphraseDelete.as_view(), name='keyphrase-delete'),
    path('actions/<int:pk>/answer/create', views.AnswerCreate.as_view(), name='answer-create'),
    path('answers/<int:pk>/edit', views.AnswerEdit.as_view(), name='answer-edit'),
    path('answers/<int:pk>/delete', views.AnswerDelete.as_view(), name='answer-delete'),
    path('keyphrases', views.KeyphrasesList.as_view(), name='keyphrases-list'),
]

frontend/haidiui/urls.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib import admin
from django.urls import path, include
import os
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('login/logout', views.LogoutView.as_view(), name='logout'),
    path('debug', views.Debug.as_view(), name='debug'),
    path('screen', views.MainScreen.as_view(), name='screen'),
    path('hsr/', include(("haidispeechreco.urls", "hsr"), namespace="hsr")),
]


BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SPOOL_DIR = os.path.join(BASE_DIR, "spool")
PIDFILE = os.path.join(SPOOL_DIR, "frontend_pidfile")
_pid = open(PIDFILE, "w")
_pid.write(str(os.getpid()))
_pid.close()

frontend/haidiui/forms.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

frontend/haidiui/views.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "HAIDI"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect, render
from . import forms
from haidispeechreco.models import Language


class Debug(LoginRequiredMixin, TemplateView):
    template_name = "ui/debug.html"

    def get_context_data(self):
        return {"langs": Language.objects.all()}


class MainScreen(TemplateView):
    template_name = "ui/screen.html"


class LoginView(FormView):
    template_name = "login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        user = authenticate(
            self.request,
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"]
        )
        if user is not None:
            login(self.request, user)
            messages.success(self.request, _("Welcome, %s" % (user.get_full_name() or user.username)))
        else:
            messages.warning(self.request, _("Username or password incorrect."))
            return self.render_to_response({"form": self.form_class})

        return redirect("home")


class LogoutView(LoginRequiredMixin, View):
    def __init__(self, *args, **kw):
        self.post = self.get
        return super().__init__(*args, **kw)

    def get(self, request):
        logout(request)
        return redirect("home")


class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect("debug")
        return render(request, "index.html")

frontend/haidiui/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block bootstrap %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock bootstrap %}
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>

    <title>{% block title %}Base template{% endblock %} - HAIDI</title>
    {% block extrahead %}
    {% endblock extrahead %}
  </head>
  <body>
    <style type="text/css">
      .badge-primary {
        font-size:23px;
      }

      .badge-danger {
        font-size:30px;
      }

      .green {color: green;}
      .red {color: red;}
      .white {color: white;}

      .progress {background-color: white;}

      .align-right {text-align: right;}
    </style>
    {% block standardcontent %}
    {% if user.is_authenticated %}
    {% include "navbar.html" %}
    {% endif %}
    <div class="container">
      <div class="jumbotron pt-3">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
          {{message}}
        </div>
        {% endfor %}
        {% block content %}
        HELO
        {% endblock content %}
      </div>
    </div>
    {% endblock standardcontent %}
  </body>
</html>

frontend/haidiui/templates/index.html
{% extends "base.html" %}{% load i18n %}
{% block title %}{% trans "Welcome" %}{% endblock %}
{% block content %}
<br>
<h1>{% trans "Welcome on HAIDI!" %}</h1>
<br><br>
<h2>{% trans "If you're an admin, please" %} <a href='{% url "login" %}'>{% trans "log in" %}</a>.</h2>
<br>
<h4>What's H.A.I.D.I. ?</h4>
<p>Is the acronym of Human Artificial Intelligence Driven Interaction. It's a Humanoid
built by the robotics group of the High School <a href="http://www.rainerum.it">Rainerum</a>
in Bolzano, Italy.</p>
<h4>How does it work?</h4>
<p>It has many pillars. For the software we use:</p>
<ul>
<li><a href="https://opencv.org/">OpenCV 3.4</a> to recognize faces and, more in general,
to process images incoming from the webcams.</li>
<li><a href="https://pypi.org/project/SpeechRecognition/">SpeechRecognition</a> with
<a href="https://cmusphinx.github.io/">Sphinx</a> to remove the noise and
listen only when a user is surely speaking first, and to transcribe
what he said then.</li>
<li><a href="https://twistedmatrix.com">Twisted</a> with <a href="https://crossbar.io/autobahn/">Autobahn</a>
for our main backend. It first receives messages from the microservices,
processes them and, if necessary, sends text or images to the robot's screen
and debug panel.</li>
<li><a href="https://www.djangoproject.com/">Django</a> with <a href="https://mariadb.org/">MariaDB</a>
as database to store the informations needed to run the robot (phrases and
answers, as example) and with <a href="https://getbootstrap.com">Bootstrap</a>,
<a href="https://jquery.com">jQuery</a> and <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebSocket">WebSockets</a>
to provide the main screen on the robot and a debug panel available for the
operators.</li>
<li><a href="https://www.arduino.cc/">Arduino</a> to move the face of the robot and to turn
on and off the leds on it.</li>
</ul>
<p>For the hardware instead we relay on an
<a href="https://www.nvidia.com/it-it/autonomous-machines/embedded-systems-dev-kits-modules/">Nvidia Jetson TX1</a>
who runs the whole software and the main screen.</p>
<h4>The components</h4>
<ul>
<li>Face recognition</li>
<li>Speech recognition</li>
<li>Backend</li>
<li>Frontend</li>
</ul></div>
{% endblock %}

frontend/haidiui/templates/login.html
{% extends "base.html" %}{% load i18n %}

{% block title %}{% trans "Provide your credentials" %}{% endblock %}

{% block content %}
<h1>{% trans "Provide your credentials" %}</h1>
<br>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-lg btn-warning" style="color:white;" value="{% trans 'Log-in' %}">
</form>
{% endblock %}

frontend/haidiui/templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">HAIDI</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'debug' %}">
          <i class="fas fa-cog" aria-hidden="true"></i>&nbsp;
          {% trans "Control panel" %}
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'hsr:actions-list' %}">
          <i class="fas fa-briefcase" aria-hidden="true"></i>&nbsp;
          {% trans "Actions" %}
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'hsr:keyphrases-list' %}">
          <i class="fas fa-key" aria-hidden="true"></i>&nbsp;
          {% trans "Keyphrases" %}
        </a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a href="#" class="nav-link">{{ user.get_full_name }} ({{user.username}})</a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">
          <i class="fas fa-hammer" aria-hidden="true"></i>&nbsp;
          {% trans "Administration" %}
        </a>
      </li>
      {% endif %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">
          <i class="fas fa-sign-out-alt" aria-hidden="true"></i>&nbsp;
          {% trans "Logout" %}
        </a>
      </li>
    </ul>
  </div>
</nav>